//
// Created by gaston on 22/04/18.
//

#ifndef BROKER_BROKER_HANDLER_H
#define BROKER_BROKER_HANDLER_H

#define BROKER_REQ_MSG 3
#define BROKER_RESP_MSG 4
#define INCOMING_MSG_SHM 5
#define INCOMING_MSG_COUNT_SHM 6
#define INCOMING_MSG_SEM 7


#define MAX_INCOMING_MSG 10

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 8080



#endif //BROKER_BROKER_HANDLER_H
