//
// Created by gaston on 22/04/18.
//

#ifndef BROKER_BROKER_HANDLER_H
#define BROKER_BROKER_HANDLER_H

#define BROKER_REQ_MSG 3
#define BROKER_RESP_MSG 4
#define INCOMING_MSG_QUEUE 5
#define BROKER_IDS_SHM 6

#define MAX_CLIENTS 10

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 8080



#endif //BROKER_BROKER_HANDLER_H
