/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumar.h"

#include <stdio.h>

int *
sumar_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Suma = %d\n", *argp + 1);

	return &result;
}
