/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMAR_H_RPCGEN
#define _SUMAR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define sumar_prg 0x30000001
#define sumar_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  int * sumar_1(int *, CLIENT *);
extern  int * sumar_1_svc(int *, struct svc_req *);
extern int sumar_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  int * sumar_1();
extern  int * sumar_1_svc();
extern int sumar_prg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMAR_H_RPCGEN */
