#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define ENTRANCE_DOORS 3
#define MUSEUM_CAP 10
#define TOUR_CAP 3


#define MUSEUM_CAP_SEM 1
#define MUSEUM_OPEN_SEM 2
#define MUSEUM_TOUR_COUNT_SEM 3
#define MUSEUM_TOUR_START_SEM 4

#define MUSEUM_CAP_SHM 1
#define MUSEUM_OPEN_SHM 2
#define MUSEUM_TOUR_COUNT_SHM 3

const int EXIT_DOOR_REQ_MSG = 2 * ENTRANCE_DOORS;
const int EXIT_DOOR_RESP_MSG = EXIT_DOOR_REQ_MSG + 1;
const int TOUR_REQ_MSG = EXIT_DOOR_RESP_MSG + 1;
const int TOUR_RESP_MSG = TOUR_REQ_MSG + 1;

#endif