all:
	g++ entranceDoor.c -o entranceDoor
	g++ exitDoor.c -o exitDoor
	g++ personGen.c -o personGen
	g++ person.c -o person
	g++ guide.c -o guide
	g++ admin.c -o admin
	g++ main.c -o main
clean:
	rm main entranceDoor exitDoor personGen person guide admin
	ipcrm --all